version: '3'

services:
  web:
    build: .
    command: rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: petstore_development
  redis:
    image: redis:latest
