# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

pets = Pet.create([
  {name:"Sadie",species:"Porcupine, north american",age:43},
  {name:"Sadie",species:"Grizzly bear",age:33},
  {name:"Daisy",species:"Heron, grey",age:97},
  {name:"Molly",species:"Vulture, bengal",age:81},
  {name:"Bailey",species:"Cat, jungle",age:36},
  {name:"Sadie",species:"Red hartebeest",age:48},
  {name:"Bailey",species:"Kalahari scrub robin",age:52},
  {name:"Lucy",species:"Sandgrouse, yellow-throated",age:14},
  {name:"Molly",species:"Orca",age:49},
  {name:"Buddy",species:"Gecko, ring-tailed",age:47},
  {name:"Max",species:"White-rumped vulture",age:35},
  {name:"Lucy",species:"California sea lion",age:39},
  {name:"Molly",species:"Skunk, striped",age:47},
  {name:"Buddy",species:"Owl, burrowing",age:9},
  {name:"Charlie",species:"Porcupine, indian",age:83},
  {name:"Max",species:"Magpie, australian",age:52},
  {name:"Molly",species:"Mocking cliffchat",age:63},
  {name:"Bailey",species:"Oystercatcher, blackish",age:99},
  {name:"Molly",species:"Long-necked turtle",age:66},
  {name:"Daisy",species:"Pied butcher bird",age:75},
  {name:"Lucy",species:"Porcupine, tree",age:58},
  {name:"Bailey",species:"Fowl, helmeted guinea",age:3},
  {name:"Lucy",species:"Iguana, land",age:96},
  {name:"Maggie",species:"Marten, american",age:60},
  {name:"Bailey",species:"African red-eyed bulbul",age:78},
  {name:"Molly",species:"Toucan, red-billed",age:11},
  {name:"Lola",species:"Euro wallaby",age:96},
  {name:"Maggie",species:"White stork",age:1},
  {name:"Sadie",species:"Ring-necked pheasant",age:24},
  {name:"Maggie",species:"European wild cat",age:5},
  {name:"Lucy",species:"Crested porcupine",age:96},
  {name:"Sadie",species:"Possum, western pygmy",age:46},
  {name:"Lola",species:"Red phalarope",age:51},
  {name:"Max",species:"Flightless cormorant",age:57},
  {name:"Bailey",species:"Western pygmy possum",age:67},
  {name:"Maggie",species:"Mynah, indian",age:46},
  {name:"Lucy",species:"Fox, arctic",age:23},
  {name:"Lola",species:"Yellow-necked spurfowl",age:13},
  {name:"Charlie",species:"Great skua",age:76},
  {name:"Buddy",species:"Asian elephant",age:38},
  {name:"Molly",species:"Penguin, magellanic",age:30},
  {name:"Buddy",species:"Galapagos sea lion",age:1},
  {name:"Buddy",species:"Gray langur",age:5},
  {name:"Maggie",species:"Vulture, lappet-faced",age:74},
  {name:"Bailey",species:"Raven, cape",age:81},
  {name:"Lola",species:"Dassie",age:35},
  {name:"Max",species:"Egyptian goose",age:11},
  {name:"Buddy",species:"California sea lion",age:4},
  {name:"Max",species:"Roe deer",age:35},
  {name:"Max",species:"Drongo, fork-tailed",age:8},
  {name:"Molly",species:"Nile crocodile",age:40},
  {name:"Charlie",species:"Crane, wattled",age:92},
  {name:"Molly",species:"Eurasian beaver",age:49},
  {name:"Max",species:"Dog, african wild",age:8},
  {name:"Bailey",species:"Spotted hyena",age:78},
  {name:"Charlie",species:"Wildebeest, blue",age:40},
  {name:"Lucy",species:"Roadrunner, greater",age:5},
  {name:"Max",species:"Turkey, wild",age:82},
  {name:"Max",species:"Burmese black mountain tortoise",age:98},
  {name:"Max",species:"Blesbok",age:96},
  {name:"Bailey",species:"Little blue penguin",age:55},
  {name:"Sadie",species:"Brazilian tapir",age:65},
  {name:"Max",species:"Tenrec, tailless",age:59},
  {name:"Bailey",species:"Stork, greater adjutant",age:31},
  {name:"Bailey",species:"Stork, saddle-billed",age:71},
  {name:"Maggie",species:"Pale-throated three-toed sloth",age:6},
  {name:"Max",species:"Sambar",age:58},
  {name:"Bailey",species:"Field flicker",age:32},
  {name:"Lola",species:"Macaw, blue and yellow",age:43},
  {name:"Bailey",species:"Lapwing (unidentified)",age:94},
  {name:"Molly",species:"Vulture, oriental white-backed",age:95},
  {name:"Charlie",species:"Bettong, brush-tailed",age:91},
  {name:"Sadie",species:"Cormorant, javanese",age:24},
  {name:"Maggie",species:"Asian foreset tortoise",age:35},
  {name:"Lucy",species:"Little blue penguin",age:67},
  {name:"Lola",species:"Australian sea lion",age:97},
  {name:"Lola",species:"Lemming, collared",age:55},
  {name:"Maggie",species:"American black bear",age:98},
  {name:"Sadie",species:"Sloth, hoffman's",age:52},
  {name:"Max",species:"Verreaux's sifaka",age:19},
  {name:"Sadie",species:"Magistrate black colobus",age:75},
  {name:"Sadie",species:"Superb starling",age:76},
  {name:"Maggie",species:"Parrot, hawk-headed",age:25},
  {name:"Bailey",species:"Kalahari scrub robin",age:94},
  {name:"Maggie",species:"Blue and yellow macaw",age:71},
  {name:"Maggie",species:"Rufous-collared sparrow",age:7},
  {name:"Buddy",species:"Vicuna",age:45},
  {name:"Molly",species:"Cat, european wild",age:91},
  {name:"Charlie",species:"White-nosed coatimundi",age:14},
  {name:"Lucy",species:"Field flicker",age:33},
  {name:"Charlie",species:"Magellanic penguin",age:11},
  {name:"Lola",species:"Rattlesnake, dusky",age:94},
  {name:"Daisy",species:"Sage grouse",age:6},
  {name:"Charlie",species:"Grey-footed squirrel",age:8},
  {name:"Bailey",species:"Hartebeest, coke's",age:85},
  {name:"Daisy",species:"Constrictor, eastern boa",age:71},
  {name:"Daisy",species:"Eastern box turtle",age:70},
  {name:"Max",species:"Kinkajou",age:53},
  {name:"Bailey",species:"Yellow-billed hornbill",age:5},
  {name:"Sadie",species:"Deer, savannah",age:66}])