default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 'db'
  username: postgres
  password: test123

development:
  <<: *default
  database: petstore_development

test:
  <<: *default
  database: petstore_test

production:
  <<: *default
  database: petstore_production
  username: petstore
  password: <%= ENV['PETSTORE_DATABASE_PASSWORD'] %>
