# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Pet.create([
             { "name": 'Marla', "species": 'Ferret', "age": 68, "price": 27.46 },
             { "name": 'Talya', "species": 'Monkey', "age": 96, "price": 595.18 },
             { "name": 'Man', "species": 'Parrot', "age": 7, "price": 678.13 },
             { "name": 'Estrellita', "species": 'Monkey', "age": 97, "price": 16.92 },
             { "name": 'Babara', "species": 'Guinea Pig', "age": 66, "price": 88.12 },
             { "name": 'Lolita', "species": 'Lizard', "age": 42, "price": 314.59 },
             { "name": 'Rollins', "species": 'Hamster', "age": 52, "price": 812.63 },
             { "name": 'Mikkel', "species": 'Lizard', "age": 45, "price": 998.13 },
             { "name": 'Jaime', "species": 'Ferret', "age": 96, "price": 278.71 },
             { "name": 'Ame', "species": 'Parrot', "age": 55, "price": 894.49 },
             { "name": 'Adelheid', "species": 'Lizard', "age": 100, "price": 266.47 },
             { "name": 'Kipp', "species": 'Cat', "age": 22, "price": 450.42 },
             { "name": 'Binnie', "species": 'Hamster', "age": 15, "price": 93.33 },
             { "name": 'Erastus', "species": 'Hamster', "age": 82, "price": 150.44 },
             { "name": 'Tadd', "species": 'Hamster', "age": 41, "price": 26.69 },
             { "name": 'Lauretta', "species": 'Rabbit', "age": 83, "price": 719.3 },
             { "name": 'Avictor', "species": 'Guinea Pig', "age": 24, "price": 30.49 },
             { "name": 'Lark', "species": 'Parrot', "age": 71, "price": 41.09 },
             { "name": 'Matthieu', "species": 'Lizard', "age": 10, "price": 405.65 },
             { "name": 'Adina', "species": 'Rabbit', "age": 2, "price": 162.2 },
             { "name": 'Claribel', "species": 'Guinea Pig', "age": 0, "price": 57.39 },
             { "name": 'Margot', "species": 'Rabbit', "age": 97, "price": 73.87 },
             { "name": 'Arney', "species": 'Guinea Pig', "age": 8, "price": 428.76 },
             { "name": 'Huberto', "species": 'Gerbil', "age": 70, "price": 376.23 },
             { "name": 'Othella', "species": 'Parrot', "age": 86, "price": 641.72 },
             { "name": 'Feliza', "species": 'Hamster', "age": 8, "price": 334.2 },
             { "name": 'Fina', "species": 'Dog', "age": 25, "price": 192.78 },
             { "name": 'Selena', "species": 'Cat', "age": 62, "price": 620.51 },
             { "name": 'Odie', "species": 'Cat', "age": 44, "price": 78.03 },
             { "name": 'Sam', "species": 'Parrot', "age": 61, "price": 480.86 },
             { "name": 'Laurette', "species": 'Guinea Pig', "age": 10, "price": 591.77 },
             { "name": 'Reilly', "species": 'Ferret', "age": 38, "price": 550.15 },
             { "name": 'Halsey', "species": 'Lizard', "age": 46, "price": 21.03 },
             { "name": 'Edvard', "species": 'Lizard', "age": 18, "price": 458.33 },
             { "name": 'Geralda', "species": 'Hamster', "age": 94, "price": 701.22 },
             { "name": 'Seana', "species": 'Hamster', "age": 30, "price": 746.78 },
             { "name": 'Tadeo', "species": 'Cat', "age": 5, "price": 294.58 },
             { "name": 'Sybila', "species": 'Guinea Pig', "age": 1, "price": 879.99 },
             { "name": 'Merlina', "species": 'Guinea Pig', "age": 76, "price": 38.58 },
             { "name": 'Westbrooke', "species": 'Lizard', "age": 39, "price": 602.35 },
             { "name": 'Garrot', "species": 'Guinea Pig', "age": 15, "price": 995.02 },
             { "name": 'Sal', "species": 'Parrot', "age": 54, "price": 659.66 },
             { "name": 'Marcellina', "species": 'Dog', "age": 86, "price": 368.33 },
             { "name": 'Lindsay', "species": 'Ferret', "age": 79, "price": 428.29 },
             { "name": 'Ermentrude', "species": 'Cat', "age": 42, "price": 131.41 },
             { "name": 'Selia', "species": 'Lizard', "age": 78, "price": 825.29 },
             { "name": 'Charis', "species": 'Guinea Pig', "age": 84, "price": 551.5 },
             { "name": 'Angel', "species": 'Parrot', "age": 16, "price": 778.1 },
             { "name": 'Antone', "species": 'Rabbit', "age": 48, "price": 128.44 },
             { "name": 'Reiko', "species": 'Cat', "age": 30, "price": 323.83 },
             { "name": 'Friederike', "species": 'Lizard', "age": 1, "price": 626.74 },
             { "name": 'Steffi', "species": 'Cat', "age": 14, "price": 227.39 },
             { "name": 'Nikolos', "species": 'Rabbit', "age": 49, "price": 129.79 },
             { "name": 'Marilin', "species": 'Cat', "age": 99, "price": 984.51 },
             { "name": 'Sibley', "species": 'Ferret', "age": 47, "price": 184.91 },
             { "name": 'Tonia', "species": 'Guinea Pig', "age": 52, "price": 477.87 },
             { "name": 'Darya', "species": 'Guinea Pig', "age": 24, "price": 403.86 },
             { "name": 'Debera', "species": 'Parrot', "age": 26, "price": 824.75 },
             { "name": 'Noam', "species": 'Gerbil', "age": 68, "price": 480.28 },
             { "name": 'Tova', "species": 'Guinea Pig', "age": 58, "price": 956.43 },
             { "name": 'Cecily', "species": 'Parrot', "age": 68, "price": 281.01 },
             { "name": 'Muriel', "species": 'Hamster', "age": 94, "price": 348.19 },
             { "name": 'Adolphe', "species": 'Hamster', "age": 35, "price": 996.62 },
             { "name": 'Josi', "species": 'Cat', "age": 44, "price": 854.38 },
             { "name": 'Aida', "species": 'Monkey', "age": 95, "price": 597.09 },
             { "name": 'Kain', "species": 'Gerbil', "age": 52, "price": 399.46 },
             { "name": 'Byran', "species": 'Parrot', "age": 15, "price": 415.59 },
             { "name": 'Rockie', "species": 'Dog', "age": 41, "price": 594.38 },
             { "name": 'Ellette', "species": 'Dog', "age": 63, "price": 296.43 },
             { "name": 'Helaina', "species": 'Rabbit', "age": 45, "price": 779.6 },
             { "name": 'Rafa', "species": 'Hamster', "age": 46, "price": 277.74 },
             { "name": 'Ramsey', "species": 'Ferret', "age": 44, "price": 601.99 },
             { "name": 'Chloris', "species": 'Rabbit', "age": 78, "price": 799.58 },
             { "name": 'Teddy', "species": 'Gerbil', "age": 58, "price": 18.12 },
             { "name": 'Vassily', "species": 'Dog', "age": 88, "price": 69.01 },
             { "name": 'Eadmund', "species": 'Hamster', "age": 45, "price": 290.43 },
             { "name": 'Cristiano', "species": 'Lizard', "age": 26, "price": 705.06 },
             { "name": 'Sibylle', "species": 'Cat', "age": 44, "price": 690.66 },
             { "name": 'Piper', "species": 'Guinea Pig', "age": 94, "price": 385.91 },
             { "name": 'Gillian', "species": 'Ferret', "age": 55, "price": 361.43 },
             { "name": 'Ashia', "species": 'Lizard', "age": 86, "price": 765.82 },
             { "name": 'Alair', "species": 'Lizard', "age": 31, "price": 534.84 },
             { "name": 'Flin', "species": 'Cat', "age": 3, "price": 592.78 },
             { "name": 'Letta', "species": 'Guinea Pig', "age": 89, "price": 127.4 },
             { "name": 'Nicki', "species": 'Ferret', "age": 45, "price": 909.75 },
             { "name": 'James', "species": 'Dog', "age": 82, "price": 23.59 },
             { "name": 'Eziechiele', "species": 'Parrot', "age": 36, "price": 544.39 },
             { "name": 'Jecho', "species": 'Dog', "age": 60, "price": 336.83 },
             { "name": 'Jenilee', "species": 'Lizard', "age": 91, "price": 849.4 },
             { "name": 'Reinaldo', "species": 'Parrot', "age": 2, "price": 496.06 },
             { "name": 'Duane', "species": 'Parrot', "age": 49, "price": 442.15 },
             { "name": 'Alec', "species": 'Hamster', "age": 39, "price": 209.81 },
             { "name": 'Karrie', "species": 'Monkey', "age": 70, "price": 159.18 },
             { "name": 'Gipsy', "species": 'Guinea Pig', "age": 24, "price": 267.69 },
             { "name": 'Kathrine', "species": 'Gerbil', "age": 41, "price": 531.79 },
             { "name": 'Luce', "species": 'Cat', "age": 86, "price": 290.96 },
             { "name": 'Bobbette', "species": 'Lizard', "age": 21, "price": 730.32 },
             { "name": 'Chet', "species": 'Monkey', "age": 5, "price": 1.25 },
             { "name": 'Brien', "species": 'Monkey', "age": 49, "price": 882.45 },
             { "name": 'Skippy', "species": 'Cat', "age": 95, "price": 415.25 }
           ])
